### ISSUE TITLE
Requirements for oemthermostat 1.1: pypi-publisher

### ISSUE THREAD

**Issue by MartinHjelmare** [Cadair/openenergymonitor_thermostat#1]
- This library supports an integration in Home Assistant.
- This library installs all development requirements also for production installs.
- One of the development requirements is pypi-publisher which pins gitpython==0.3.6.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would only install the requirements needed for production in production mode, ie by updating `install_requires` in `setup.py`. Currently the only requirement in production mode for this library is the `requests` library.

Thanks for your support of Home Assistant!

**Comment by Cadair** [comment]
Hello :wave: 

I have just repackaged and released a bug fix version with only requests as the only dependency. Should I open a PR to hass core to bump the dep or is that done automatically?

**Comment by MartinHjelmare** [comment]
Great! Please open a PR to bump the library version in Home Assistant. Thank you! 👍
